kind: pipeline
name: default

steps:
- name: docker
  image: plugins/docker
  settings:
    username: 
      from_secret: docker_username
    password: 
      from_secret: docker_password
    repo: chrispruitt/${DRONE_REPO_NAME}
    tags: latest
    squash: true
    auto_tag: true
    cache_from:
      - "chrispruitt/${DRONE_REPO_NAME}:latest"
